### ISSUE TITLE
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by smilelovea** [smilelovea/lolChess#13]
```
 const onDrop_handler = event => {
    event.preventDefault();
    const id = event.dataTransfer.getData('text');
    event.target.appendChild(document.getElementById(id));
 };
```

holder를 여러번 클릭하여 드래그 하려고 할 경우 
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'. 와 같은 에러 발생

-> appendChild는 Node만 추가할 수 있음.
append 는 DOMString,Node 가능

**Comment by smilelovea** [comment]
appendChild를 append로 수정하였을 경우 holder를 드래그 할 때 null이라는 글자가 생겨 드래그됨

**Comment by smilelovea** [comment]
-> appendChild는 Node만 추가할 수 있음.
append 는 DOMString,Node 가능

때문에 위의 코드처럼 html element인 div를 추가하거나

 
```
const onDrop_handler = event => {
    event.preventDefault();
    const id = event.dataTransfer.getData('text');
    event.target.appendChild(document.createTextNode(document.getElementById(id)));
 }; 
```

위처럼 textnode를 추가하였는데 드랍된 위치에 블럭이 이동하지 않고 [object HTMLDivElement] 라는 글자가 생기는 문제가 발생합니다.

**Comment by jongfeel** [comment]
document.createTextNode의 경우는 html innerText의 값을 넣는 거라 문제(?)라고 생각한 현상이 일어나는 것 같습니다.

정확히 어떤 걸 해야 하기 때문에 이런 코드를 짜게 되었는지 더 설명을 해줄 수 있을까요?

**Comment by smilelovea** [comment]
box를 담고있는 holder를 두 번 이상 드래그 할 때 (box가 드래그 앤 드랍되는 대상이라 holder를 굳이 드래그 할 필요는 없지만 실수로라도 드래그 될 경우) 오류가 생기는것을 막고자 합니다.

  appendchild()로 추가하려는 document.getElementById(id)가 노드 타입이 아니라 문자열 타입이기 때문에 에러가 생긴다고 생각하여 노드 타입으로 변경하기 위해 document.createTextNode나 innerHTML 을 사용했는데 위와 같은 문제들이 생겼습니다,,

**Comment by jongfeel** [comment]
``` javascript
event.dataTransfer.getData('text');
```
이걸 했을 때 holder 라면 id 값이 없을 테니까 id 값이 없는 경우인 null이거나 undefined인지 확인하고
아닐 때만

``` javascript
event.target.append(document.getElementById(id));
```

이렇게 해주면 되지 않을까 싶네요?
