### ISSUE TITLE
box끼리 겹쳐지는 문제

### ISSUE THREAD

**Issue by smilelovea** [smilelovea/lolChess#17]
1. box를 drag&drop할 때 box위에 box가 올라가는(겹쳐지는) 문제가 생김.
2. 드래그앤드랍 하려는 box를 다른곳으로 드랍하지 않고 다시 제자리에 드랍할 경우 아래와 같은 에러 발생.
Failed to execute 'append' on 'Element': The new child element contains the parent.
 
=> box에는 node가 추가되지 않도록 한다.

- box를 box가 있는 holder로 드랍했을 때 서로의 위치가 바뀔수 있도록 하고자 함.

**Comment by smilelovea** [comment]
2. 드래그앤드랍 하려는 box를 다른곳으로 드랍하지 않고 다시 제자리에 드랍할 경우 아래와 같은 에러 발생.
Failed to execute 'append' on 'Element': The new child element contains the parent.
=> class가 "box"인 div에 onDrop = "return false"를 추가하여 해결

**Comment by jongfeel** [comment]
onDrop="return false"

이 코드가 제대로 동작하는지 확인해 보세요.
onDrop은 함수여야 하는데 단순 string 값이면 에러가 나게 되어 있습니다.

**Comment by smilelovea** [comment]
겉으로 보기에 동작은 하는데 console에서 에러가 나서
아래와 같이 수정하였습니다

```
<div onDrop = {onDrop_prevent}>

const onDrop_prevent = event => {
    event.preventDefault();
    event.stopPropagation();
}
```
