### ISSUE TITLE
Check out pull request

### ISSUE THREAD

**Issue by jongfeel** [smilelovea/lolChess#18]
제가 pull request 드린 코드대로 수정하신 후에 다시 commit을 하셔서 
pull request가 의미가 없어지게 되었는데요.

#16 

pull request 리뷰를 하고 merge를 해주시면 좋고 아니면 의견을 더 주시면 좋습니다.
지금은 소스코드 충돌 체크를 하고 다시 merge 할 수 있는 상태로 돌려 놨어요.

**Comment by smilelovea** [comment]
감사합니다!
미팅 후에 pull request 확인을 못하고 바로 수정을 해서 충돌이 일어났습니다..
