### ISSUE TITLE
(2020-10-12 계획) '사진을 어떻게 넣을것인가'에 대해 생각해보고 방법 찾아보기.

### ISSUE THREAD

**Issue by smilelovea** [smilelovea/lolChess#47]
- 13:40~14:40
'사진을 어떻게 넣을것인가'에 대해 생각해보고 방법 찾아보기.

**Comment by jongfeel** [comment]
'사진을 어떻게 넣을것인가'에 대해 생각해보고 방법 찾아보기.

이게 제목이어야 할 것 같습니다.

**Comment by smilelovea** [comment]
수정하였습니다!

**Comment by smilelovea** [comment]
실천사항:

아래 링크에 찾아본 내용을 정리하였습니다. 
https://www.notion.so/201012-1dfa936bfa60476a94e0ca80e703c42e

**Comment by jongfeel** [comment]
First of all
- 제가 그냥 코멘트를 달아 드렸는데, assignee에 절 넣어주셔야 합니다.

방법에 대한 내용을 잘 찾아서 적어주신 것 같습니다.
img tag는 적용해 보면 눈에 보이니까 해보시면 될 거 같네요.

**Comment by jongfeel** [comment]
그리고 `how`에 집중하는 모습이 보여서 정상이긴 한데요.
- 배우는 입장에서의 자세가 정상이라는 뜻

사실 `why`, `what`에 대한 내용도 있어야 합니다.

이미지가 왜 나와야 하고
어떤 이미지가 나와야 하고
어디에서 이미지를 가져와서 어떤 배치로 보여줘야 하고
그 이미지들이 보여진 후에 어떤 기능들을 사용할 수 있는지 혹은 다른 기능에 연관이 있는지에 대한
**내용**이 있어야 하겠죠.

**Comment by smilelovea** [comment]
넵 확인했습니다!
