### ISSUE TITLE
(2020-10-14 계획) Champbox 컴포넌트에 사진 삽입.

### ISSUE THREAD

**Issue by smilelovea** [smilelovea/lolChess#48]
- 15:00 ~ 16:00
`<img>`태그를 사용하여 chessboard.js 의 Champbox 컴포넌트에 사진 삽입.

**Comment by smilelovea** [comment]
실천 사항:
https://www.notion.so/201014-82640b64edc5460799c91f3091bff1df 에 작성하였습니다. 

+)
상대 경로 표기법에 대한 정리가 필요

**Comment by jongfeel** [comment]
절 assigned 하셨는데 논의할 내용이 어떤건가요?

**Comment by smilelovea** [comment]
계획-실천 작성할때 assigned 해야하는것인줄 알고 하였는데 논의 사항이 있을 경우 하도록 하겠습니다!
