### ISSUE TITLE
2020-10-15, 1st offline meetup

### ISSUE THREAD

**Issue by jongfeel** [smilelovea/lolChess#50]
동생 분인 승현님도 참석하셔서 더 좋은 시간이었던 것 같습니다.
옛날 얘기랑 평소에 제가 해드렸던 얘기를 많이 한 것 같고요.

### 누군가 자유를 억압해야 할 수 있는 환경

- 그렇게 하지 않아도 충분히 방법을 찾을 수 있습니다.
- 스스로 방법을 찾고 동기 부여를 할 때가 제일 값진 시간을 쓰고 열정을 쓰실 수 있게 되요.

### 학원 선택의 문제

- 아직 고민중이시면 속는셈 치고 한번 겪어 보는 것도 나쁘지 않을 것 같습니다.
- 어차피 공부는 스스로 해야 한다는 원칙을 지켜 보시면 사실 어떤 학원을 다니던지 크게 중요하지는 않을 것 같네요.

### Home coming day

- 승현님도 참석하고 싶어하는 것 같으니 현재 진행 중인 멘티의 한 분으로 참석해 주시면 좋을 듯 합니다.
- 참석해서 자리를 빛내 주시면 나중에 "그냥 갈 껄" 하며 후회하는 일은 안생기실걸요(?)

### 책 선물

비전공자 분들한테는 이런 내용을 접하지 않고 계속 프로그래밍만 하다 보면 뭔가 답답한 벽이 생기게 마련인데
컴퓨터에 대한 내용을 조금 이해하고 진행해 보시면 뭘 알아야 할지에 대한 힌트를 얻는데 상당한 도움이 되실 거에요.

![image](https://user-images.githubusercontent.com/17442457/96148313-1c7b4c00-0f43-11eb-9ef9-75e6aa4a4287.png)

**Comment by smilelovea** [comment]
책 감사합니다 열심히 읽어보겠습니다ㅎㅎㅎ 홈커밍데이도 참석하고싶어요..! 😃
