### ISSUE TITLE
Clean up closed issues

### ISSUE THREAD

**Issue by jongfeel** [smilelovea/lolChess#53]
현재 진행 중인 작업과 완료된 작업의 파악이 어려운 것 같은데

제가 작성한 issue에 한해서 close가 가능한 것들은 정리하겠습니다.

매번 issue 작성 하기 전에 현재 상황 체크를 해 주시고 진행하면 좋겠습니다.

**Comment by jongfeel** [comment]
제가 작성하고 확인한 issue는 close 완료 했습니다.

**Comment by smilelovea** [comment]
네 확인했습니다
