### ISSUE TITLE
Review meeting missed

### ISSUE THREAD

**Issue by jongfeel** [smilelovea/lolChess#56]
원래 10월 22일이 미팅날인데 제가 캘린더에 미팅을 등록하지 않았었다는 걸 23일에 알았습니다.

어쨌든 제가 미리 등록을 안해놔서 못한 거니까 제 실수입니다.

제가 잊고 있더라도 혜빈님이 저한테 얘기해 주셨을수도 있는데 얘기 안해 주신 이유가 뭔지 궁금합니다.

일단은 10월 29일 목요일로 일정 잡아 놓을께요.

**Comment by smilelovea** [comment]
앗 오프라인 미팅을 해서 다음주로 착각하고 일정 확인해볼 생각을 못했네요,, 확인했습니다!
