### ISSUE TITLE
Would you change review meeting cycle?

### ISSUE THREAD

**Issue by jongfeel** [smilelovea/lolChess#62]
제목 그대로 리뷰 미팅 주기를 1달로 변경하거나
아예 필요할때만 github를 통해서 comment 하는 방향으로 하는건 어떤지 하는 제안입니다.

그동안 온라인 리뷰 미팅 했던 날짜를 적어보면 아래와 같습니다.
- 05-13
- 06-19
- 07-10
- 07-31
- 08-28
- 10-08
- 11-05

이번에 한다고 하면 11-05인데 이 마저도 논의할 내용을 아직도 알려주지 않으셔서 
진행 여부가 불투명한 상태입니다.

혜빈님의 의견을 들어보고 싶네요.

**Comment by smilelovea** [comment]
넵 comment가 필요한 경우 github를 통해서 comment 해주시는 방향이 좋다고 생각합니다..!

**Comment by jongfeel** [comment]
저도 이런 케이스는 처음이라 정리를 좀 해야 할 듯 합니다.
우선 큰 틀은

- 온라인 리뷰 미팅 없음
- 논의가 필요할 떄 마다 issue에 assignee를 넣어 논의 진행
- 코드 리뷰가 필요할 때 마다 pull request에 reviewer를 넣어 논의 진행

이렇게 될 것 같습니다.

그렇다고 해도 가끔은 온라인으로 대화 하는 것이 더 좋을 수도 있기 때문에
필요하다면 요청해서 **리뷰 미팅을 비정기적**으로라도 가져보면 좋겠습니다.
제가 먼저 요청하지 않는다는 점만 주의하시면 될 것 같아요.

기존 룰은 지켜서 하는게 좋을 것 같아요.
지금도 잘 하고 계신 부분도 있고 미흡한 부분도 있습니다.

- 주당 시간을 얼마나 쓸 지에 대한 계획 => 그리고 실천
  - 1 주 혹은 2주 간격으로 따로 정리해서 달성률 체크 필요
- 기간 내에 해야할 목표치 설정 => milestone
- 진행한 작업 시간마다 어떤 작업을 할 건지에 대한 내용 미리 정한 후 작업 진행 => 잘 되고 있음
  - 작업 진행 후 어떤 결과를 얻었는지 간단히 내용 정리 필요 (코드 포함)
  - 노션에 따로 정리했다면 노션 링크 첨부 해야 함
- milestone에 계획한대로 안됐을 경우 계획 변경을 하고 어떻게 해서 변경이 이루어졌는지 내용 정리
  - 회고를 권장하지는 않지만, 시행착오를 줄일 수 있도록 지속적 계획 변경을 진행
- 되도록이면 코드 리뷰를 요청해서 리뷰를 받을 것을 권장

뭔가 안지켜질때마다 제가 계속 issue로 지적하고 물어볼 때 그제서야 몰랐다는 듯이 하는 것 보다
조금씩 시간 들여서 작업 계획, 시간, 진행 상황, milestone 등 체크하시고 문서 혹은 issue로 정리 하셔서 진행해 주세요.
다른 분들 어떻게 하나 구경도 좀 해보시고요, 원하는 걸 얻어가려고 많이 준비하고 저와 대화하려는 분이 결국 저한테 더 많은 것을 얻어가게 되어 있습니다.

오늘도 리뷰 미팅 날이긴 한데 이제 리뷰 미팅이 없어졌으니
새로운 룰로 적용 시작해서 잘 진행해 보셨으면 좋겠습니다.

**Comment by smilelovea** [comment]
넵 확인했습니다 감사합니다!
