### ISSUE TITLE
(2020-12-02 계획) chessboard에 이미지가 복사되어 드롭되는 기능 추가

### ISSUE THREAD

**Issue by smilelovea** [smilelovea/lolChess#72]
14:00~15:00 )
champbox의 이미지가 chessboard에 이미지가 복사되어 드롭되는 기능 추가

**Comment by smilelovea** [comment]
https://www.notion.so/201202-c2b435006fa74e429977b6b2b5054f43

**Comment by smilelovea** [comment]
17:00~18:00)
Cannot read property 'src' of null 오류 해결하기

**Comment by jongfeel** [comment]
노션에 정리한 내용에 힌트가 있습니다. 알고 계실지도 모르겠네요.

**Comment by smilelovea** [comment]
감사합니다..! copyimg 에 id를 추가하는것이 맞을까요?!

**Comment by jongfeel** [comment]
> 감사합니다..! copyimg 에 id를 추가하는것이 맞을까요?!

해보시고 판단해 봐도 좋을 것 같아요.

**Comment by smilelovea** [comment]
@jongfeel 멘토님 ! 계속 찾아보다가 방향이 안잡혀서 질문드립니다 
copyimg.setAttribute("id", original.id); 로 복사된 이미지에 id를 추가하였는데 복사된 이미지를 옮길 때 data가 공백이 나와서 

```
const dropCopy = (event) => {
  event.preventDefault();
  const data = event.dataTransfer.getData("image");
  // copyimg.src = original.src;
  if (data) {
    let original = document.getElementById(data);
    let copyimg = original.cloneNode(true);
    event.target.append(copyimg);

    console.log(copyimg.id);
  } else if (!data) {
    console.log("없음");
  }
};
```
와 같이 조건문을 만들어서 data가 공백인 복사된 이미지를 옮기려고 생각을 바꾸었는데요 
복사된 이미지를 옮기기 위해 어떻게 지정해야 할지, 제가 작성하고 있는 방향이 맞는건지 잘 모르겠어서 질문드립니다..!
id를 추가하는것이 맞는지도 확신이 없습니다,, 어떤 것을 더 찾아보아야 할까요??

**Comment by jongfeel** [comment]
제가 빠른 시일 (2~3일) 내에 분석해 보고 내용을 추가해 보겠습니다.
코드는 main branch에 있는 내용인거죠?

혹시 변경된게 있으면 commit, push 해 주세요.
이유는 pull reqeust를 통한 코드 리뷰가 진행될 수 있기 때문입니다.

그 동안 다른 branch에서 작업해 주세요.

**Comment by smilelovea** [comment]
넵 확인했습니다 
조건문 만들었던것을 커밋을 안해놔서 오늘 했고 현재 main branch에 있는 내용입니다
감사합니다..!

**Comment by jongfeel** [comment]
제가 노션에 정리한 내용에 힌트가 있다고 했잖아요.

> copyimg 의 data 값이 없음.
copyimg에도 id값을 주어야 함.

data 값이 어디에서 부터 오고 있고, id 값을 주고 있는지 체크해 보면 어떨까요?

**Comment by smilelovea** [comment]
네 확인해보겠습니다~!
